version: "3.7"
services:
  mysql:
    container_name: face_mysql
    image: mysql:5.7
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: asdf4112
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: face_visitor

  face_api:
    container_name: face_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: asdf4112
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/face_visitor?autoReconnect=true&useSSL=false
    restart: always
    ports:
          - 5001:5001
    links:
      - mysql
    depends_on:
      - mysql
