spring:
  servlet:
    multipart:
      max-file-size: 7MB
      max-request-size: 7MB
  jpa:
    properties:
      hibernate.default_batch_fetch_size: 1000

  application:
    name: "FACE_VISITOR"
  profiles:
    active: dev
    include: key






