spring:
  servlet:
    multipart:
      max-file-size: 7MB
      max-request-size: 7MB


  application:
    name: "FACE_VISITOR"
  profiles:
    active: dev
    include: key, aws




jpa:
  properties:
    hibernate.default_batch_fetch_size: 1000



